name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine

    - name: Build package
      run: python -m build

    - name: Verify metadata
      run: twine check dist/*

    - name: Upload build artifacts (for debugging/manual runs)
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*

    # Publish only when triggered by a tag push matching v*.*.*:
    - name: Publish to PyPI with Twine
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_API_TOKEN }}
      run: |
        twine upload --skip-existing dist/*
